104 - Favourite project
FEBFES/FF-TM-BACK pull request #106
Opened 2023-04-12 20:12 UTC by IvanShish

Так как поменял расположение миграций, чтобы все работало, надо сделать следующее:
Добавить к каждой миграции в таблице `databasechangelog` в поле `fileName` строку "changes/", чтобы в итоге fileName был примерно таким: "/db/changelog/changes/*.yaml"

2023-04-13 17:38 UTC, VladisStep requested changes

2023-04-13 17:38 UTC, VladisStep commented on src/main/java/com/febfes/fftmback/controller/ProjectController.java
> +        Long userId = user.getId();
userId используется один раз, так что думаю ее можно убрать

2023-04-13 17:38 UTC, VladisStep commented on src/main/java/com/febfes/fftmback/controller/ProjectController.java
> +        Long userId = user.getId();
Аналогично

2023-04-13 17:38 UTC, VladisStep commented on src/main/java/com/febfes/fftmback/service/impl/ProjectServiceImpl.java
> +        projectEntity.setIsFavourite(projectRepository.isProjectFavourite(id, ownerId));
кмк выставление статус "Избранное" лучше не делать в этом методе. Этот метод должен возвращать просто проект. Я предлагаю вернуть этот метод, и сделать отельный метод, который будет возвращать проект для определенного юзера. Что думаешь?

2023-04-13 17:38 UTC, VladisStep commented on src/main/java/com/febfes/fftmback/service/impl/ProjectServiceImpl.java
> +        ProjectEntity projectEntity = projectRepository.findById(id)
Как раз тут можно было бы заменить на метод getProject(String id) вместо обращения к репозиторию

2023-04-13 17:38 UTC, VladisStep commented on src/main/java/com/febfes/fftmback/service/impl/ProjectServiceImpl.java
> +        if (patchDto.key().equals("isFavourite")) {
Мне кажется, что тут можно было бы реализовать паттерн цепочка ответственности, где каждое звено это обработчик конкретного поля. Пока оно у нас одно, но на будущее. Что думешь?

2023-04-15 06:48 UTC, IvanShish commented
![image](https://user-images.githubusercontent.com/42907301/232193388-52b1f8fc-8f09-4cf2-a936-8c3670b08e45.png)
Поменять в базе нужно fileName у миграций

2023-04-16 08:45 UTC, VladisStep approved these changes

2023-04-16 08:45 UTC, merged