184 - project refactoring
FEBFES/FF-TM-BACK pull request #185
Opened 2024-04-22 19:52 UTC by IvanShish

https://github.com/FEBFES/FF-TM-BACK/issues/184

2024-04-22 19:53 UTC, IvanShish commented
Поделил ProjectService на более мелкие интерфейсы и попробовал применить декоратор на практике)

2024-04-22 20:35 UTC, IvanShish commented
Почему-то такое чувство, что в `ProjectManagementServiceDecorator` не создаются `CompletableFuture.runAsync(() -> columnService.createDefaultColumnsForProject(projectId));` колонки именно вот здесь в гитхабе в Actions, поэтому не проходят тесты. Там пишет "DASHBOARD SIZE: 0". Видимо в другом потоке не может создать, хз

2024-04-22 20:36 UTC, Sabfes commented
ну да, в целом согласен

2024-04-22 20:37 UTC, Sabfes requested changes
Доработать

2024-04-22 20:37 UTC, Sabfes commented on src/main/java/com/febfes/fftmback/service/impl/ColumnServiceImpl.java
> +    public static final List<String> DEFAULT_COLUMNS = List.of("BACKLOG", "IN PROGRESS", "REVIEW", "DONE");
тут нету модульности

2024-04-23 20:09 UTC, VladisStep commented on src/test/java/com/febfes/fftmback/integration/DashboardControllerTests.java
>          taskService.createTask(
дублирование

2024-04-23 20:11 UTC, VladisStep commented on src/test/java/com/febfes/fftmback/integration/DashboardControllerTests.java
> +        while (true) {
добавить выход из цикла в случае долгой работы

2024-04-23 20:12 UTC, VladisStep commented on src/test/java/com/febfes/fftmback/integration/EntityOrderTest.java
> +        while (getDashboard().columns().size() != DEFAULT_COLUMNS.size()) {
удалить while

2024-04-23 20:14 UTC, VladisStep commented on src/test/java/com/febfes/fftmback/integration/ProjectControllerTest.java
> +        while (true) {
удалить while

2024-04-23 20:14 UTC, VladisStep commented on src/test/java/com/febfes/fftmback/integration/TaskFilterTest.java
> +                columnId1 = dashboard1.columns().get(0).id();
можно переделать через стрим

2024-04-23 20:15 UTC, VladisStep commented on src/test/java/com/febfes/fftmback/integration/TaskFilterTest.java
>          taskService.createTask(
дублирование кода

2024-04-30 10:09 UTC, IvanShish commented on src/main/java/com/febfes/fftmback/service/project/DashboardServiceImpl.java
> +    private final ColumnService columnService;
хз
ну в принципе можно указывать, можно не указывать, не важно

2024-04-30 10:24 UTC, VladisStep commented on src/main/java/com/febfes/fftmback/service/project/ProjectMemberServiceImpl.java
> +        ProjectWithMembersProjection project = projectRepository.getProjectByIdAndUserId(projectId, userId)
> Возвращаем проект для определенного пользователя. С ролью этого пользователя на проекте, с favourite_project

Это я понял после того как зашел в репозиторий и разобрался в запросе. Изначально путает. Предлагаю переименовать в getProjectForUser или подобным образом

2024-04-30 10:31 UTC, IvanShish commented on src/main/java/com/febfes/fftmback/service/project/ProjectManagementServiceImpl.java
> +        return ProjectMapper.INSTANCE.projectToProjectDto(projectEntity);
А в чем преимущество выноса мапинга в контроллер? 
Я почитал, https://github.com/EduardoPires/EquinoxProject/issues/49 здесь к примеру и на стэк оверфлоу https://stackoverflow.com/questions/21554977/should-services-always-return-dtos-or-can-they-also-return-domain-models как то все кардинально расходится. Одни пишут, что сервисы должны защищать энтити и возвращать дто, другие пишут что возвращая энтити, можно для разных эндпоинтов возвращать разные дто

По поводу инстансов тоже хз. Типа то что ты говорил что тестировать проще будет? Зато добавится больше зависимостей да и небольшое увеличение кода https://stackoverflow.com/questions/66503012/using-spring-bean-vs-a-static-instance-pattern-for-mapstruct

Из другого источника:

> Ultimately, the best approach will depend on the specific needs of the project. It is recommended to consider factors such as performance requirements, ease of integration with existing frameworks, and the complexity of the mapping logic before deciding on the best approach for using Mapstruct.

2024-04-30 11:07 UTC, VladisStep commented on src/main/java/com/febfes/fftmback/service/project/ProjectManagementServiceImpl.java
> +        return ProjectMapper.INSTANCE.projectToProjectDto(projectEntity);
> А в чем преимущество выноса мапинга в контроллер?

Метод `editProject` должен только обновлять проект, а маппингом уже должен заниматься кто-то другой. Вообще в этом сервисе dto возвращает только этот метод, все остальные возвращают сущности. Так как дто это представление для клиента, то и преобразование должно делаться не в сервисе бизнес логики проектов, а в другом месте.  Так же этот метод я не могу использовать в других сервисах, так как он возвращает дто, то есть если мне понадобятся какие-то еще манипуляции с сущностью то придется либо получать заново её из базы, либо преобразовывать обратно из дто в сущность.

> Одни пишут, что сервисы должны защищать энтити и возвращать дто, другие пишут что возвращая энтити, можно для разных эндпоинтов возвращать разные дто

Тут согласен, что тема холиварная. Можно сделать отдельный метод для этого или вынести в другое место. Предложил вынести в контроллер, так как мне кажется, что так более логично. То есть контроллер получает сущность и преобразовывает её к виду, который он отправит

> По поводу инстансов тоже хз.

+++ изменится  `ProjectMapper.INSTANCE.projectToProjectDto(projectEntity)` -> `mapper.projectToProjectDto(projectEntity)`
+++ можно легко мокать
+++ простота и понятность (добавляем зависимость так же как и обычные сервисы)
--- добавится `private final ProjectMapper mapper` в сервисы (так как используем RequiredArgsConstructor, то проблем с большим количеством параметров в конструкторе не будет)

> Зато добавится больше зависимостей

Если говорить в глобальном плане, то количество зависимостей не изменится. То есть у нас сервис и так зависит от мапера и все проблемы мапера будут влиять на сервис. Но на уровне кода у нас добавится файнал переменная, которая будет инжектится спрингом

> небольшое увеличение кода 

В нашем случае это добавление файнал переменной

2024-04-30 11:18 UTC, IvanShish commented on src/main/java/com/febfes/fftmback/service/project/ProjectManagementServiceImpl.java
> +        return ProjectMapper.INSTANCE.projectToProjectDto(projectEntity);
ок

2024-05-01 10:31 UTC, merged