189 - file service refactoring
FEBFES/FF-TM-BACK pull request #190
Opened 2024-05-04 08:41 UTC by IvanShish

2024-05-11 08:56 UTC, VladisStep requested changes

2024-05-11 08:56 UTC, VladisStep commented on src/main/java/com/febfes/fftmback/domain/common/EntityType.java
> +    private static String filesFolder;
filesFolder используется только в TASK, но вынесен в общий код. Аналогично с userPicFolder и USER_PIC. Лучше сделать, чтобы получение этих переменных происходило в этих значениях.

2024-05-11 08:56 UTC, VladisStep commented on src/main/java/com/febfes/fftmback/service/FileService.java
> +    Optional<FileEntity> saveFile(Long userId, Long entityId, EntityType entityType, MultipartFile file);
Не совсем понимаю для чего нам два метода? В каком случае нужно использовать метод, который не выбрасывает исключение? Когда лень обрабатывать их?)

2024-05-16 19:47 UTC, IvanShish commented on src/main/java/com/febfes/fftmback/domain/common/EntityType.java
> +    private static String filesFolder;
Как думаешь, как лучше сделать. Щас потестил и понял, что `@Value` можно использовать только в бинах. В енаме там null. Пока придумал два варианта, как в метод `getFilePath` передавать папку. Ну в обоих случаях нужно `@Value("${files.folder}")` и с user pic также перенести в FileServiceImpl. 

1. Создать postConstruct в FileServiceImpl, в котором будет вызываться метод putFolder (см. ниже) и заполняться мапа foldersMap.
2. С помощью функции `folderGetter` (см. ниже) передавать в `getFilePath` папку.

Плюсы первого метода: 

- не нужна доп переменная в `getFilePath` (будет типа `public abstract String getFilePath(MultipartFile file, String folder, String idForPath);`);
- не нужна функция folderGetter, в которой в теории может быть куча переменных

Минус первого метода: каждый раз при создании нового enum надо не забывать в метод postConstruct в FileServiceImpl добавлять вызов метода putFolder.

Но мне все равно пока первый метод кажется лучше, пока ничего другого не придумал.

Конечно можно вообще отойти от енама и переделать в компонент какой-то, но мне хотелось с такой нестандартной реализацией енама попробовать че-то поделать


![image](https://github.com/FEBFES/FF-TM-BACK/assets/42907301/6fff3030-c1b6-45d8-bcea-7ca1d4d4f1e3)

2024-05-16 19:50 UTC, IvanShish commented on src/main/java/com/febfes/fftmback/service/FileService.java
> +    Optional<FileEntity> saveFile(Long userId, Long entityId, EntityType entityType, MultipartFile file);
Ну первый метод, который выбрасывает исключение, использовать в случаях, когда нужно сохранить только один файл. И типа выдавать эту ошибку в контроллер. Как это сделано в `FileController` в `saveUserPic`

Второй метод, не выбрасывающий, для случая, когда за один раз сохраняется несколько файлов. В таком случае я подумал странно выбрасывать исключение, лучше просто не сохранять такой файл, а все остальные сохранить, которые получится. Или лучше просто сделать везде, чтобы исключение выбрасывалось?

2024-05-18 08:03 UTC, VladisStep commented on src/main/java/com/febfes/fftmback/service/FileService.java
> +    Optional<FileEntity> saveFile(Long userId, Long entityId, EntityType entityType, MultipartFile file);
> Или лучше просто сделать везде, чтобы исключение выбрасывалось?
 
 Считаю, что лучше оставить один метод с выбрасыванием исключения. Разница в этих методах в том, что один делает сохранение, а второй навешивает на первый try-catch (странно, что в имплементации это не так реализовано). И, кажется, логика обработки ошибки должна быть в вызывающем методе.

2024-05-18 09:14 UTC, VladisStep commented on src/main/java/com/febfes/fftmback/domain/common/EntityType.java
> +    private static String filesFolder;
[а_что_если...](https://github.com/FEBFES/FF-TM-BACK/files/15360909/_._.patch) просто передаем название переменной из пропертей и получаем значение, где нужно

> не нужна функция folderGetter, в которой в теории может быть куча переменных

а разве в postConstruct не будет той же проблемы? То есть в нем мы прописываем много путов

2024-05-18 14:57 UTC, IvanShish commented on src/main/java/com/febfes/fftmback/service/FileService.java
> +    Optional<FileEntity> saveFile(Long userId, Long entityId, EntityType entityType, MultipartFile file);
![image](https://github.com/FEBFES/FF-TM-BACK/assets/42907301/92c467c5-343b-41ee-9f27-ce4ee562d82b)

Просто еще здесь видишь как красиво сделано, когда не надо обрабатывать исключение в .map(...)

А так придется обрабатывать

2024-05-18 15:55 UTC, VladisStep approved these changes
LGTM

2024-05-18 15:59 UTC, merged