Task Comments
FEBFES/FF-TM-BACK pull request #202
Opened 2024-06-05 18:49 UTC by VladisStep

2024-06-06 16:28 UTC, IvanShish requested changes

2024-06-06 16:28 UTC, IvanShish commented on src/main/java/com/febfes/fftmback/controller/TaskCommentController.java
> +    @ApiCreate(path = "add-comment")
я бы поменял на `{taskId}/comments` и убрал из TaskCommentDto taskId

2024-06-06 16:28 UTC, IvanShish commented on src/main/resources/db/changelog/changes/2024.06.01-add-task-comment-entity.yaml
> +                  type: varchar(1000)
```suggestion
                  type: text
```
Мб на текст поменять? Там же длинный коммент в теории может быть, больше 1000

2024-06-06 16:28 UTC, IvanShish commented on src/main/java/com/febfes/fftmback/service/impl/TaskCommentServiceImpl.java
> +                Sort.by(Sort.Direction.ASC, "createDate")
Пока так можно оставить, но потом наверное надо сделать, чтобы с фронта приходила сортировка

2024-06-06 16:28 UTC, IvanShish commented on src/main/java/com/febfes/fftmback/domain/dao/TaskCommentEntity.java
> +    @JoinColumn(name = "creator_id", referencedColumnName = "id")
а че здесь по N+1 все четко все норм нет никаких лишних запросов?

2024-06-10 16:50 UTC, VladisStep commented on src/main/java/com/febfes/fftmback/controller/TaskCommentController.java
> +    @ApiCreate(path = "add-comment")
с первый ок

id специально оставил, чтобы в будущем было легче сделать удаление или редактирование

2024-06-10 18:21 UTC, merged