196 - deadline notification
FEBFES/FF-TM-BACK pull request #203
Opened 2024-06-07 20:20 UTC by IvanShish

2024-06-10 17:17 UTC, VladisStep requested changes

2024-06-10 17:17 UTC, VladisStep commented on src/main/java/com/febfes/fftmback/controller/SseNotificationController.java
> +    public void sendMessageToTheUser(String message, String username) {
А зачем артикли прописывать в названии метода? Только делает ее длиннее

2024-06-10 17:17 UTC, VladisStep commented on src/main/java/com/febfes/fftmback/controller/TestWSController.java
> +//    @OnMessage
Удоли

2024-06-10 17:17 UTC, VladisStep commented on src/main/java/com/febfes/fftmback/service/impl/TaskServiceDecorator.java
> +public class TaskServiceDecorator implements TaskService {
Предлагаю более осмысленно называть декораторы, так как не понятно когда нужно использовать оригинальный сервис, а когда декоратор

2024-06-10 17:17 UTC, VladisStep commented on src/main/java/com/febfes/fftmback/service/impl/TaskServiceDecorator.java
> +    public static final String USER_ID = "userId";
Может эти константы хранить в ентити? Так можно будет их использовать в разных сервисах и будет понятно из какой ентит берется название поля

2024-06-10 17:17 UTC, VladisStep commented on src/main/java/com/febfes/fftmback/service/impl/TaskServiceDecorator.java
> +        if (editTask.getDeadlineDate() != null) {
че дублируешь код,тварь?

2024-06-10 18:22 UTC, IvanShish commented on src/main/java/com/febfes/fftmback/controller/TestWSController.java
> +//    @OnMessage
не, это на будущее, я специально не удалил

2024-06-12 20:02 UTC, IvanShish commented on src/main/java/com/febfes/fftmback/service/impl/TaskServiceDecorator.java
> +    public static final String USER_ID = "userId";
1. но userId и taskId у нас используются не только у TaskEntity, а много где
2. эти константы для мапы используются, то есть в теории я мог назвать как угодно эти поля, они не относятся к названию полей в энтити

2024-06-12 20:13 UTC, IvanShish commented on src/main/java/com/febfes/fftmback/service/impl/TaskServiceDecorator.java
> +        if (editTask.getDeadlineDate() != null) {
потом поправлю в следующем PR

2024-06-12 20:13 UTC, IvanShish commented on src/main/java/com/febfes/fftmback/service/impl/TaskServiceDecorator.java
> +public class TaskServiceDecorator implements TaskService {
потом поправлю в следующем PR

2024-06-12 20:15 UTC, IvanShish commented
Здесь https://github.com/FEBFES/FF-TM-BACK/issues/205 поправлю то что не исправил

2024-06-13 18:18 UTC, VladisStep approved these changes
LGTM

2024-06-14 19:35 UTC, merged