201 - notification changes
FEBFES/FF-TM-BACK pull request #204
Opened 2024-06-09 07:52 UTC by IvanShish

2024-06-10 17:36 UTC, VladisStep requested changes

2024-06-10 17:36 UTC, VladisStep commented on src/main/java/com/febfes/fftmback/controller/NotificationController.java
> +    public void changeIsRead(@PathVariable Long notificationId) {
не то название

2024-06-10 17:36 UTC, VladisStep commented on src/main/java/com/febfes/fftmback/schedule/DeleteNotificationJob.java
> +    public void execute(JobExecutionContext jobExecutionContext) {
Не совсем понимаю зачем вообще нужен статус isRead.  Пользователь получает уведомление о дедлайне и если не хочет его видеть, то удаляет его.

2024-06-15 07:46 UTC, IvanShish commented on src/main/java/com/febfes/fftmback/schedule/DeleteNotificationJob.java
> +    public void execute(JobExecutionContext jobExecutionContext) {
Прочитано уведомление или нет. Так же у всех реализовано

2024-06-15 07:47 UTC, merged