Тип и приоритет таски
FEBFES/FF-TM-BACK pull request #99
Opened 2023-03-11 09:59 UTC by VladisStep

2023-03-12 08:47 UTC, IvanShish requested changes

2023-03-12 08:47 UTC, IvanShish commented on src/main/java/com/febfes/fftmback/dto/constant/TaskPriority.java
> +package com.febfes.fftmback.dto.constant;
мне кажется стоит перенести этот enum в папку domain

2023-03-12 08:47 UTC, IvanShish commented on src/main/java/com/febfes/fftmback/mapper/TaskMapper.java
> +        return str == null ? null : TaskPriority.valueOf(str.toUpperCase());
```suggestion
        return isNull(str) ? null : TaskPriority.valueOf(str.toUpperCase());
```

2023-03-12 08:47 UTC, IvanShish commented on src/main/java/com/febfes/fftmback/mapper/TaskMapper.java
> +        return priority == null ? null : priority.name().toLowerCase();
```suggestion
        return isNull(priority) ? null : priority.name().toLowerCase();
```

Не знаю на счет того, что когда в строку преобразовываем, надо именно в lower case делать, а не upper

2023-03-12 08:47 UTC, IvanShish commented on src/main/java/com/febfes/fftmback/service/TaskTypeService.java
> +    List<String> DEFAULT_TASK_TYPES = List.of("bug", "feature", "research", "question");
Уверен что лучше в интерфейсе такие константы объявлять?

2023-03-12 08:47 UTC, IvanShish commented on src/main/java/com/febfes/fftmback/service/impl/ProjectServiceImpl.java
> +            taskTypeService.deleteAllTypesByProjectId(id);
а там не каскадное удаление типов тасок? По идее же тогда когда удаляется проект должны удаляться и колонки и задачи, относящиеся к проекту
Но если более глобально этот вопрос брать, то по идее удаление проектов вообще не нужно

2023-03-12 08:47 UTC, IvanShish commented on src/main/java/com/febfes/fftmback/service/impl/TaskServiceImpl.java
> +    private static final String RECEIVED_TASKS_SIZE_LOG = "Received tasks size: {}";
Кстати хоть это и я написал, но мне это не особо нравится как выглядит) Но и как лучше это переделать - тоже хз. Может у тебя какая-то идея есть?)

2023-03-12 08:47 UTC, IvanShish commented on src/main/java/com/febfes/fftmback/service/impl/TaskServiceImpl.java
> +        if (task.getTaskType() != null) {
```suggestion
        if (nonNull(task.getTaskType())) {
```

2023-03-12 08:47 UTC, IvanShish commented on src/main/java/com/febfes/fftmback/service/impl/TaskServiceImpl.java
> +        if (typeName == null || projectId == null) {
```suggestion
        if (isNull(typeName) || isNull(projectId)) {
```

2023-03-12 08:47 UTC, IvanShish commented on src/main/java/com/febfes/fftmback/service/impl/TaskServiceImpl.java
> +            task.setTaskType(null);
А вообще есть смысл задавать в этом случае task type = null? Может оставить task type тот, который был (не особо понял логику, но по идее он null и будет в данном случае)

2023-03-12 08:47 UTC, IvanShish commented on src/main/java/com/febfes/fftmback/service/impl/TaskServiceImpl.java
> +                .ifPresentOrElse(task::setTaskType, () -> task.setTaskType(null));
И вот здесь тоже. Обязательно нужно task type занулять?

2023-03-12 08:47 UTC, IvanShish commented on src/main/java/com/febfes/fftmback/service/impl/TaskTypeServiceImpl.java
> +    @Autowired
почему не через private final? Зачем autowired?

2023-03-12 08:47 UTC, IvanShish commented on src/main/java/com/febfes/fftmback/service/impl/TaskTypeServiceImpl.java
> +        log.info("Created default columns with names: {}", DEFAULT_TASK_TYPES);
```suggestion
        log.info("Created default task types: {} for project with id={}", DEFAULT_TASK_TYPES, projectId);
```

2023-03-12 08:47 UTC, IvanShish commented on src/main/resources/db/changelog/0.0.9-add-priority-and-tag-to-task.yaml
> +                  type: int
А почему int? Я же так понял будет храниться как строка. Или как?

2023-03-12 08:47 UTC, IvanShish commented on src/main/resources/db/changelog/0.0.9-add-priority-and-tag-to-task.yaml
> +                  name: project_id
А стоит добавить уникальность по двум полям: name и project id? Чтобы не создавать одинаковые task type для одного проекта. Возможно было бы сложно это сделать, так как в разных регистрах могли бы названия писаться, но ты вроде приводишь все task type к нижнему регистру, поэтому могло бы сработать

2023-03-12 08:47 UTC, IvanShish commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: /db/changelog/0.0.8-change-user-id-in-refresh-token.yaml
А почему в каком-то странном порядке миграции идут?) Вроде это конечно ни на что не влияет, но как-то не очень смотрится)

2023-03-12 08:47 UTC, IvanShish commented on src/test/java/com/febfes/fftmback/integration/TaskControllerTest.java
> +    void createAndTaskWithType() {
```suggestion
    void createTaskWithTypeTest() {
```

2023-03-12 08:47 UTC, IvanShish commented on src/test/java/com/febfes/fftmback/integration/TaskControllerTest.java
> +    void createAndTaskWithPriority() {
```suggestion
    void createTaskWithPriorityTest() {
```

2023-03-12 08:47 UTC, IvanShish commented on src/test/java/com/febfes/fftmback/integration/TaskControllerTest.java
> +        String taskType = TaskTypeService.DEFAULT_TASK_TYPES.get(0);
Видимо для этого ты добавил DEFAULT_TASK_TYPES именно в интерфейс, а не в имплементацию)
Но я все равно хз насколько это правильно, надо бы как-то изучить этот вопрос)

2023-03-13 16:25 UTC, VladisStep commented on src/main/java/com/febfes/fftmback/service/impl/TaskServiceImpl.java
> +            task.setTaskType(null);
Не будет, маппер по дефолту добавляет пустой объект, а потом при сохранении возникают проблемы

2023-03-13 16:28 UTC, VladisStep commented on src/main/resources/db/changelog/0.0.9-add-priority-and-tag-to-task.yaml
> +                  type: int
там храниться значение enum, а оно как инт записывается

2023-03-14 18:37 UTC, merged